"""create tasks table

Revision ID: 37c9d0da97fc
Revises: e93fb9f5249a
Create Date: 2026-06-26 07:41:01.849389

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '37c9d0da97fc'
down_revision: Union[str, Sequence[str], None] = 'e93fb9f5249a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tasks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('location_id', sa.UUID(), nullable=True),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('est_effort_min', sa.Integer(), nullable=True),
    sa.Column('assigned_to', sa.UUID(), nullable=True),
    sa.Column('recurrence_rule', sa.Text(), nullable=True),
    sa.Column('series_id', sa.UUID(), nullable=True),
    sa.Column('origin_capture_id', sa.UUID(), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default='now()', nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default='now()', nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('row_version', sa.BigInteger(), server_default=sa.FetchedValue(), nullable=False),
    sa.ForeignKeyConstraint(['assigned_to'], ['users.id'], ),
    sa.ForeignKeyConstraint(['origin_capture_id'], ['captures.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###

    # Hand-add: row_version trigger (reuses existing set_row_version function)
    op.execute("""
        CREATE TRIGGER trg_tasks_row_version
        BEFORE INSERT OR UPDATE ON tasks
        FOR EACH ROW EXECUTE FUNCTION set_row_version()
    """)

    # Close the loop: now that tasks exists, add FK from captures.promoted_task_id
    op.create_foreign_key(
        "fk_captures_promoted_task_id",
        "captures", "tasks",
        ["promoted_task_id"], ["id"],
    )


def downgrade() -> None:
    """Downgrade schema."""
    # Drop FK from captures.promoted_task_id first
    op.drop_constraint("fk_captures_promoted_task_id", "captures", type_="foreignkey")

    # Drop trigger before table
    op.execute("DROP TRIGGER IF EXISTS trg_tasks_row_version ON tasks")

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tasks')
    # ### end Alembic commands ###
