"""create location_types and locations

Revision ID: b31d0d582548
Revises: 37c9d0da97fc
Create Date: 2026-06-26 10:11:56.845029

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b31d0d582548'
down_revision: Union[str, Sequence[str], None] = '37c9d0da97fc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('location_types',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('sort', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('row_version', sa.BigInteger(), server_default=sa.FetchedValue(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('locations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('code', sa.Text(), nullable=True),
    sa.Column('type_id', sa.UUID(), nullable=False),
    sa.Column('parent_id', sa.UUID(), nullable=True),
    sa.Column('lat', sa.Float(), nullable=True),
    sa.Column('lng', sa.Float(), nullable=True),
    sa.Column('geometry', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('photo_url', sa.Text(), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('row_version', sa.BigInteger(), server_default=sa.FetchedValue(), nullable=False),
    sa.CheckConstraint('parent_id <> id', name='ck_locations_no_self_parent'),
    sa.ForeignKeyConstraint(['parent_id'], ['locations.id'], ),
    sa.ForeignKeyConstraint(['type_id'], ['location_types.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # Hand-added: row_version triggers
    op.execute("CREATE TRIGGER trg_location_types_row_version BEFORE INSERT OR UPDATE ON location_types FOR EACH ROW EXECUTE FUNCTION set_row_version()")
    op.execute("CREATE TRIGGER trg_locations_row_version BEFORE INSERT OR UPDATE ON locations FOR EACH ROW EXECUTE FUNCTION set_row_version()")
    # Hand-added: close deferred FK tasks.location_id -> locations.id
    op.create_foreign_key('fk_tasks_location', 'tasks', 'locations', ['location_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_tasks_location', 'tasks', type_='foreignkey')
    op.execute("DROP TRIGGER IF EXISTS trg_locations_row_version ON locations")
    op.execute("DROP TRIGGER IF EXISTS trg_location_types_row_version ON location_types")
    op.drop_table('locations')
    op.drop_table('location_types')
    # ### end Alembic commands ###
