"""create captures table

Revision ID: e93fb9f5249a
Revises: ac84e2503302
Create Date: 2026-06-25 20:05:05.959492

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e93fb9f5249a'
down_revision: Union[str, Sequence[str], None] = 'ac84e2503302'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('captures',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('raw_text', sa.Text(), nullable=False),
    sa.Column('location_hint', sa.Text(), nullable=True),
    sa.Column('location_id', sa.UUID(), nullable=True),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('promoted_task_id', sa.UUID(), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default='now()', nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default='now()', nullable=False),
    sa.Column('deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('row_version', sa.BigInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )

    op.execute("""
        CREATE TRIGGER trg_captures_row_version
        BEFORE INSERT OR UPDATE ON captures
        FOR EACH ROW EXECUTE FUNCTION set_row_version()
    """)


def downgrade() -> None:
    """Downgrade schema."""
    op.execute("DROP TRIGGER IF EXISTS trg_captures_row_version ON captures")
    op.drop_table('captures')
